/*
 * Generated by gdbus-codegen 2.40.2. DO NOT EDIT.
 *
 * The license of this code is the same as for the source it was derived from.
 */

#ifdef HAVE_CONFIG_H
#  include "config.h"
#endif

#include "mapClient.h"

#include <string.h>
#ifdef G_OS_UNIX
#  include <gio/gunixfdlist.h>
#endif

typedef struct
{
  GDBusArgInfo parent_struct;
  gboolean use_gvariant;
} _ExtendedGDBusArgInfo;

typedef struct
{
  GDBusMethodInfo parent_struct;
  const gchar *signal_name;
  gboolean pass_fdlist;
} _ExtendedGDBusMethodInfo;

typedef struct
{
  GDBusSignalInfo parent_struct;
  const gchar *signal_name;
} _ExtendedGDBusSignalInfo;

typedef struct
{
  GDBusPropertyInfo parent_struct;
  const gchar *hyphen_name;
  gboolean use_gvariant;
} _ExtendedGDBusPropertyInfo;

typedef struct
{
  GDBusInterfaceInfo parent_struct;
  const gchar *hyphen_name;
} _ExtendedGDBusInterfaceInfo;

typedef struct
{
  const _ExtendedGDBusPropertyInfo *info;
  guint prop_id;
  GValue orig_value; /* the value before the change */
} ChangedProperty;

static void
_changed_property_free (ChangedProperty *data)
{
  g_value_unset (&data->orig_value);
  g_free (data);
}

static gboolean
_g_strv_equal0 (gchar **a, gchar **b)
{
  gboolean ret = FALSE;
  guint n;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  if (g_strv_length (a) != g_strv_length (b))
    goto out;
  for (n = 0; a[n] != NULL; n++)
    if (g_strcmp0 (a[n], b[n]) != 0)
      goto out;
  ret = TRUE;
out:
  return ret;
}

static gboolean
_g_variant_equal0 (GVariant *a, GVariant *b)
{
  gboolean ret = FALSE;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  ret = g_variant_equal (a, b);
out:
  return ret;
}

G_GNUC_UNUSED static gboolean
_g_value_equal (const GValue *a, const GValue *b)
{
  gboolean ret = FALSE;
  g_assert (G_VALUE_TYPE (a) == G_VALUE_TYPE (b));
  switch (G_VALUE_TYPE (a))
    {
      case G_TYPE_BOOLEAN:
        ret = (g_value_get_boolean (a) == g_value_get_boolean (b));
        break;
      case G_TYPE_UCHAR:
        ret = (g_value_get_uchar (a) == g_value_get_uchar (b));
        break;
      case G_TYPE_INT:
        ret = (g_value_get_int (a) == g_value_get_int (b));
        break;
      case G_TYPE_UINT:
        ret = (g_value_get_uint (a) == g_value_get_uint (b));
        break;
      case G_TYPE_INT64:
        ret = (g_value_get_int64 (a) == g_value_get_int64 (b));
        break;
      case G_TYPE_UINT64:
        ret = (g_value_get_uint64 (a) == g_value_get_uint64 (b));
        break;
      case G_TYPE_DOUBLE:
        {
          /* Avoid -Wfloat-equal warnings by doing a direct bit compare */
          gdouble da = g_value_get_double (a);
          gdouble db = g_value_get_double (b);
          ret = memcmp (&da, &db, sizeof (gdouble)) == 0;
        }
        break;
      case G_TYPE_STRING:
        ret = (g_strcmp0 (g_value_get_string (a), g_value_get_string (b)) == 0);
        break;
      case G_TYPE_VARIANT:
        ret = _g_variant_equal0 (g_value_get_variant (a), g_value_get_variant (b));
        break;
      default:
        if (G_VALUE_TYPE (a) == G_TYPE_STRV)
          ret = _g_strv_equal0 (g_value_get_boxed (a), g_value_get_boxed (b));
        else
          g_critical ("_g_value_equal() does not handle type %s", g_type_name (G_VALUE_TYPE (a)));
        break;
    }
  return ret;
}

/* ------------------------------------------------------------------------
 * Code for interface org.bluez.obex.MessageAccess1
 * ------------------------------------------------------------------------
 */

/**
 * SECTION:ObexMessageAccess1
 * @title: ObexMessageAccess1
 * @short_description: Generated C code for the org.bluez.obex.MessageAccess1 D-Bus interface
 *
 * This section contains code for working with the <link linkend="gdbus-interface-org-bluez-obex-MessageAccess1.top_of_page">org.bluez.obex.MessageAccess1</link> D-Bus interface in C.
 */

/* ---- Introspection data for org.bluez.obex.MessageAccess1 ---- */

static const _ExtendedGDBusArgInfo _obex_message_access1_method_info_set_folder_IN_ARG_folder =
{
  {
    -1,
    (gchar *) "folder",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _obex_message_access1_method_info_set_folder_IN_ARG_pointers[] =
{
  &_obex_message_access1_method_info_set_folder_IN_ARG_folder,
  NULL
};

static const _ExtendedGDBusMethodInfo _obex_message_access1_method_info_set_folder =
{
  {
    -1,
    (gchar *) "SetFolder",
    (GDBusArgInfo **) &_obex_message_access1_method_info_set_folder_IN_ARG_pointers,
    NULL,
    NULL
  },
  "handle-set-folder",
  FALSE
};

static const _ExtendedGDBusArgInfo _obex_message_access1_method_info_list_folders_IN_ARG_filters =
{
  {
    -1,
    (gchar *) "filters",
    (gchar *) "a{sv}",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _obex_message_access1_method_info_list_folders_IN_ARG_pointers[] =
{
  &_obex_message_access1_method_info_list_folders_IN_ARG_filters,
  NULL
};

static const _ExtendedGDBusArgInfo _obex_message_access1_method_info_list_folders_OUT_ARG_content =
{
  {
    -1,
    (gchar *) "content",
    (gchar *) "aa{sv}",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _obex_message_access1_method_info_list_folders_OUT_ARG_pointers[] =
{
  &_obex_message_access1_method_info_list_folders_OUT_ARG_content,
  NULL
};

static const _ExtendedGDBusMethodInfo _obex_message_access1_method_info_list_folders =
{
  {
    -1,
    (gchar *) "ListFolders",
    (GDBusArgInfo **) &_obex_message_access1_method_info_list_folders_IN_ARG_pointers,
    (GDBusArgInfo **) &_obex_message_access1_method_info_list_folders_OUT_ARG_pointers,
    NULL
  },
  "handle-list-folders",
  FALSE
};

static const _ExtendedGDBusArgInfo _obex_message_access1_method_info_list_messages_IN_ARG_folder =
{
  {
    -1,
    (gchar *) "folder",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _obex_message_access1_method_info_list_messages_IN_ARG_filter =
{
  {
    -1,
    (gchar *) "filter",
    (gchar *) "a{sv}",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _obex_message_access1_method_info_list_messages_IN_ARG_pointers[] =
{
  &_obex_message_access1_method_info_list_messages_IN_ARG_folder,
  &_obex_message_access1_method_info_list_messages_IN_ARG_filter,
  NULL
};

static const _ExtendedGDBusArgInfo _obex_message_access1_method_info_list_messages_OUT_ARG_messages =
{
  {
    -1,
    (gchar *) "messages",
    (gchar *) "a{oa{sv}}",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _obex_message_access1_method_info_list_messages_OUT_ARG_pointers[] =
{
  &_obex_message_access1_method_info_list_messages_OUT_ARG_messages,
  NULL
};

static const _ExtendedGDBusMethodInfo _obex_message_access1_method_info_list_messages =
{
  {
    -1,
    (gchar *) "ListMessages",
    (GDBusArgInfo **) &_obex_message_access1_method_info_list_messages_IN_ARG_pointers,
    (GDBusArgInfo **) &_obex_message_access1_method_info_list_messages_OUT_ARG_pointers,
    NULL
  },
  "handle-list-messages",
  FALSE
};

static const _ExtendedGDBusArgInfo _obex_message_access1_method_info_list_filter_fields_OUT_ARG_fields =
{
  {
    -1,
    (gchar *) "fields",
    (gchar *) "as",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _obex_message_access1_method_info_list_filter_fields_OUT_ARG_pointers[] =
{
  &_obex_message_access1_method_info_list_filter_fields_OUT_ARG_fields,
  NULL
};

static const _ExtendedGDBusMethodInfo _obex_message_access1_method_info_list_filter_fields =
{
  {
    -1,
    (gchar *) "ListFilterFields",
    NULL,
    (GDBusArgInfo **) &_obex_message_access1_method_info_list_filter_fields_OUT_ARG_pointers,
    NULL
  },
  "handle-list-filter-fields",
  FALSE
};

static const _ExtendedGDBusMethodInfo _obex_message_access1_method_info_update_inbox =
{
  {
    -1,
    (gchar *) "UpdateInbox",
    NULL,
    NULL,
    NULL
  },
  "handle-update-inbox",
  FALSE
};

static const _ExtendedGDBusArgInfo _obex_message_access1_method_info_push_message_IN_ARG_file =
{
  {
    -1,
    (gchar *) "file",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _obex_message_access1_method_info_push_message_IN_ARG_folder =
{
  {
    -1,
    (gchar *) "folder",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _obex_message_access1_method_info_push_message_IN_ARG_args =
{
  {
    -1,
    (gchar *) "args",
    (gchar *) "a{sv}",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _obex_message_access1_method_info_push_message_IN_ARG_pointers[] =
{
  &_obex_message_access1_method_info_push_message_IN_ARG_file,
  &_obex_message_access1_method_info_push_message_IN_ARG_folder,
  &_obex_message_access1_method_info_push_message_IN_ARG_args,
  NULL
};

static const _ExtendedGDBusArgInfo _obex_message_access1_method_info_push_message_OUT_ARG_transfer =
{
  {
    -1,
    (gchar *) "transfer",
    (gchar *) "o",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _obex_message_access1_method_info_push_message_OUT_ARG_properties =
{
  {
    -1,
    (gchar *) "properties",
    (gchar *) "a{sv}",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _obex_message_access1_method_info_push_message_OUT_ARG_pointers[] =
{
  &_obex_message_access1_method_info_push_message_OUT_ARG_transfer,
  &_obex_message_access1_method_info_push_message_OUT_ARG_properties,
  NULL
};

static const _ExtendedGDBusMethodInfo _obex_message_access1_method_info_push_message =
{
  {
    -1,
    (gchar *) "PushMessage",
    (GDBusArgInfo **) &_obex_message_access1_method_info_push_message_IN_ARG_pointers,
    (GDBusArgInfo **) &_obex_message_access1_method_info_push_message_OUT_ARG_pointers,
    NULL
  },
  "handle-push-message",
  FALSE
};

static const _ExtendedGDBusMethodInfo * const _obex_message_access1_method_info_pointers[] =
{
  &_obex_message_access1_method_info_set_folder,
  &_obex_message_access1_method_info_list_folders,
  &_obex_message_access1_method_info_list_messages,
  &_obex_message_access1_method_info_list_filter_fields,
  &_obex_message_access1_method_info_update_inbox,
  &_obex_message_access1_method_info_push_message,
  NULL
};

static const _ExtendedGDBusInterfaceInfo _obex_message_access1_interface_info =
{
  {
    -1,
    (gchar *) "org.bluez.obex.MessageAccess1",
    (GDBusMethodInfo **) &_obex_message_access1_method_info_pointers,
    NULL,
    NULL,
    NULL
  },
  "obex-message-access1",
};


/**
 * obex_message_access1_interface_info:
 *
 * Gets a machine-readable description of the <link linkend="gdbus-interface-org-bluez-obex-MessageAccess1.top_of_page">org.bluez.obex.MessageAccess1</link> D-Bus interface.
 *
 * Returns: (transfer none): A #GDBusInterfaceInfo. Do not free.
 */
GDBusInterfaceInfo *
obex_message_access1_interface_info (void)
{
  return (GDBusInterfaceInfo *) &_obex_message_access1_interface_info.parent_struct;
}

/**
 * obex_message_access1_override_properties:
 * @klass: The class structure for a #GObject<!-- -->-derived class.
 * @property_id_begin: The property id to assign to the first overridden property.
 *
 * Overrides all #GObject properties in the #ObexMessageAccess1 interface for a concrete class.
 * The properties are overridden in the order they are defined.
 *
 * Returns: The last property id.
 */
guint
obex_message_access1_override_properties (GObjectClass *klass, guint property_id_begin)
{
  return property_id_begin - 1;
}



/**
 * ObexMessageAccess1:
 *
 * Abstract interface type for the D-Bus interface <link linkend="gdbus-interface-org-bluez-obex-MessageAccess1.top_of_page">org.bluez.obex.MessageAccess1</link>.
 */

/**
 * ObexMessageAccess1Iface:
 * @parent_iface: The parent interface.
 * @handle_list_filter_fields: Handler for the #ObexMessageAccess1::handle-list-filter-fields signal.
 * @handle_list_folders: Handler for the #ObexMessageAccess1::handle-list-folders signal.
 * @handle_list_messages: Handler for the #ObexMessageAccess1::handle-list-messages signal.
 * @handle_push_message: Handler for the #ObexMessageAccess1::handle-push-message signal.
 * @handle_set_folder: Handler for the #ObexMessageAccess1::handle-set-folder signal.
 * @handle_update_inbox: Handler for the #ObexMessageAccess1::handle-update-inbox signal.
 *
 * Virtual table for the D-Bus interface <link linkend="gdbus-interface-org-bluez-obex-MessageAccess1.top_of_page">org.bluez.obex.MessageAccess1</link>.
 */

typedef ObexMessageAccess1Iface ObexMessageAccess1Interface;
G_DEFINE_INTERFACE (ObexMessageAccess1, obex_message_access1, G_TYPE_OBJECT);

static void
obex_message_access1_default_init (ObexMessageAccess1Iface *iface)
{
  /* GObject signals for incoming D-Bus method calls: */
  /**
   * ObexMessageAccess1::handle-set-folder:
   * @object: A #ObexMessageAccess1.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_folder: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-bluez-obex-MessageAccess1.SetFolder">SetFolder()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call obex_message_access1_complete_set_folder() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-set-folder",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (ObexMessageAccess1Iface, handle_set_folder),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    2,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_STRING);

  /**
   * ObexMessageAccess1::handle-list-folders:
   * @object: A #ObexMessageAccess1.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_filters: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-bluez-obex-MessageAccess1.ListFolders">ListFolders()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call obex_message_access1_complete_list_folders() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-list-folders",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (ObexMessageAccess1Iface, handle_list_folders),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    2,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_VARIANT);

  /**
   * ObexMessageAccess1::handle-list-messages:
   * @object: A #ObexMessageAccess1.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_folder: Argument passed by remote caller.
   * @arg_filter: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-bluez-obex-MessageAccess1.ListMessages">ListMessages()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call obex_message_access1_complete_list_messages() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-list-messages",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (ObexMessageAccess1Iface, handle_list_messages),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    3,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_STRING, G_TYPE_VARIANT);

  /**
   * ObexMessageAccess1::handle-list-filter-fields:
   * @object: A #ObexMessageAccess1.
   * @invocation: A #GDBusMethodInvocation.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-bluez-obex-MessageAccess1.ListFilterFields">ListFilterFields()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call obex_message_access1_complete_list_filter_fields() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-list-filter-fields",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (ObexMessageAccess1Iface, handle_list_filter_fields),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    1,
    G_TYPE_DBUS_METHOD_INVOCATION);

  /**
   * ObexMessageAccess1::handle-update-inbox:
   * @object: A #ObexMessageAccess1.
   * @invocation: A #GDBusMethodInvocation.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-bluez-obex-MessageAccess1.UpdateInbox">UpdateInbox()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call obex_message_access1_complete_update_inbox() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-update-inbox",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (ObexMessageAccess1Iface, handle_update_inbox),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    1,
    G_TYPE_DBUS_METHOD_INVOCATION);

  /**
   * ObexMessageAccess1::handle-push-message:
   * @object: A #ObexMessageAccess1.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_file: Argument passed by remote caller.
   * @arg_folder: Argument passed by remote caller.
   * @arg_args: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-bluez-obex-MessageAccess1.PushMessage">PushMessage()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call obex_message_access1_complete_push_message() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-push-message",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (ObexMessageAccess1Iface, handle_push_message),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    4,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_STRING, G_TYPE_STRING, G_TYPE_VARIANT);

}

/**
 * obex_message_access1_call_set_folder:
 * @proxy: A #ObexMessageAccess1Proxy.
 * @arg_folder: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-bluez-obex-MessageAccess1.SetFolder">SetFolder()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call obex_message_access1_call_set_folder_finish() to get the result of the operation.
 *
 * See obex_message_access1_call_set_folder_sync() for the synchronous, blocking version of this method.
 */
void
obex_message_access1_call_set_folder (
    ObexMessageAccess1 *proxy,
    const gchar *arg_folder,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "SetFolder",
    g_variant_new ("(s)",
                   arg_folder),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * obex_message_access1_call_set_folder_finish:
 * @proxy: A #ObexMessageAccess1Proxy.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to obex_message_access1_call_set_folder().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with obex_message_access1_call_set_folder().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
obex_message_access1_call_set_folder_finish (
    ObexMessageAccess1 *proxy,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * obex_message_access1_call_set_folder_sync:
 * @proxy: A #ObexMessageAccess1Proxy.
 * @arg_folder: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-bluez-obex-MessageAccess1.SetFolder">SetFolder()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See obex_message_access1_call_set_folder() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
obex_message_access1_call_set_folder_sync (
    ObexMessageAccess1 *proxy,
    const gchar *arg_folder,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "SetFolder",
    g_variant_new ("(s)",
                   arg_folder),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * obex_message_access1_call_list_folders:
 * @proxy: A #ObexMessageAccess1Proxy.
 * @arg_filters: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-bluez-obex-MessageAccess1.ListFolders">ListFolders()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call obex_message_access1_call_list_folders_finish() to get the result of the operation.
 *
 * See obex_message_access1_call_list_folders_sync() for the synchronous, blocking version of this method.
 */
void
obex_message_access1_call_list_folders (
    ObexMessageAccess1 *proxy,
    GVariant *arg_filters,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "ListFolders",
    g_variant_new ("(@a{sv})",
                   arg_filters),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * obex_message_access1_call_list_folders_finish:
 * @proxy: A #ObexMessageAccess1Proxy.
 * @out_content: (out): Return location for return parameter or %NULL to ignore.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to obex_message_access1_call_list_folders().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with obex_message_access1_call_list_folders().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
obex_message_access1_call_list_folders_finish (
    ObexMessageAccess1 *proxy,
    GVariant **out_content,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(@aa{sv})",
                 out_content);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * obex_message_access1_call_list_folders_sync:
 * @proxy: A #ObexMessageAccess1Proxy.
 * @arg_filters: Argument to pass with the method invocation.
 * @out_content: (out): Return location for return parameter or %NULL to ignore.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-bluez-obex-MessageAccess1.ListFolders">ListFolders()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See obex_message_access1_call_list_folders() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
obex_message_access1_call_list_folders_sync (
    ObexMessageAccess1 *proxy,
    GVariant *arg_filters,
    GVariant **out_content,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "ListFolders",
    g_variant_new ("(@a{sv})",
                   arg_filters),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(@aa{sv})",
                 out_content);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * obex_message_access1_call_list_messages:
 * @proxy: A #ObexMessageAccess1Proxy.
 * @arg_folder: Argument to pass with the method invocation.
 * @arg_filter: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-bluez-obex-MessageAccess1.ListMessages">ListMessages()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call obex_message_access1_call_list_messages_finish() to get the result of the operation.
 *
 * See obex_message_access1_call_list_messages_sync() for the synchronous, blocking version of this method.
 */
void
obex_message_access1_call_list_messages (
    ObexMessageAccess1 *proxy,
    const gchar *arg_folder,
    GVariant *arg_filter,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "ListMessages",
    g_variant_new ("(s@a{sv})",
                   arg_folder,
                   arg_filter),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * obex_message_access1_call_list_messages_finish:
 * @proxy: A #ObexMessageAccess1Proxy.
 * @out_messages: (out): Return location for return parameter or %NULL to ignore.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to obex_message_access1_call_list_messages().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with obex_message_access1_call_list_messages().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
obex_message_access1_call_list_messages_finish (
    ObexMessageAccess1 *proxy,
    GVariant **out_messages,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(@a{oa{sv}})",
                 out_messages);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * obex_message_access1_call_list_messages_sync:
 * @proxy: A #ObexMessageAccess1Proxy.
 * @arg_folder: Argument to pass with the method invocation.
 * @arg_filter: Argument to pass with the method invocation.
 * @out_messages: (out): Return location for return parameter or %NULL to ignore.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-bluez-obex-MessageAccess1.ListMessages">ListMessages()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See obex_message_access1_call_list_messages() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
obex_message_access1_call_list_messages_sync (
    ObexMessageAccess1 *proxy,
    const gchar *arg_folder,
    GVariant *arg_filter,
    GVariant **out_messages,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "ListMessages",
    g_variant_new ("(s@a{sv})",
                   arg_folder,
                   arg_filter),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(@a{oa{sv}})",
                 out_messages);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * obex_message_access1_call_list_filter_fields:
 * @proxy: A #ObexMessageAccess1Proxy.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-bluez-obex-MessageAccess1.ListFilterFields">ListFilterFields()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call obex_message_access1_call_list_filter_fields_finish() to get the result of the operation.
 *
 * See obex_message_access1_call_list_filter_fields_sync() for the synchronous, blocking version of this method.
 */
void
obex_message_access1_call_list_filter_fields (
    ObexMessageAccess1 *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "ListFilterFields",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * obex_message_access1_call_list_filter_fields_finish:
 * @proxy: A #ObexMessageAccess1Proxy.
 * @out_fields: (out): Return location for return parameter or %NULL to ignore.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to obex_message_access1_call_list_filter_fields().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with obex_message_access1_call_list_filter_fields().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
obex_message_access1_call_list_filter_fields_finish (
    ObexMessageAccess1 *proxy,
    gchar ***out_fields,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(^as)",
                 out_fields);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * obex_message_access1_call_list_filter_fields_sync:
 * @proxy: A #ObexMessageAccess1Proxy.
 * @out_fields: (out): Return location for return parameter or %NULL to ignore.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-bluez-obex-MessageAccess1.ListFilterFields">ListFilterFields()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See obex_message_access1_call_list_filter_fields() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
obex_message_access1_call_list_filter_fields_sync (
    ObexMessageAccess1 *proxy,
    gchar ***out_fields,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "ListFilterFields",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(^as)",
                 out_fields);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * obex_message_access1_call_update_inbox:
 * @proxy: A #ObexMessageAccess1Proxy.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-bluez-obex-MessageAccess1.UpdateInbox">UpdateInbox()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call obex_message_access1_call_update_inbox_finish() to get the result of the operation.
 *
 * See obex_message_access1_call_update_inbox_sync() for the synchronous, blocking version of this method.
 */
void
obex_message_access1_call_update_inbox (
    ObexMessageAccess1 *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "UpdateInbox",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * obex_message_access1_call_update_inbox_finish:
 * @proxy: A #ObexMessageAccess1Proxy.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to obex_message_access1_call_update_inbox().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with obex_message_access1_call_update_inbox().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
obex_message_access1_call_update_inbox_finish (
    ObexMessageAccess1 *proxy,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * obex_message_access1_call_update_inbox_sync:
 * @proxy: A #ObexMessageAccess1Proxy.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-bluez-obex-MessageAccess1.UpdateInbox">UpdateInbox()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See obex_message_access1_call_update_inbox() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
obex_message_access1_call_update_inbox_sync (
    ObexMessageAccess1 *proxy,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "UpdateInbox",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * obex_message_access1_call_push_message:
 * @proxy: A #ObexMessageAccess1Proxy.
 * @arg_file: Argument to pass with the method invocation.
 * @arg_folder: Argument to pass with the method invocation.
 * @arg_args: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-bluez-obex-MessageAccess1.PushMessage">PushMessage()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call obex_message_access1_call_push_message_finish() to get the result of the operation.
 *
 * See obex_message_access1_call_push_message_sync() for the synchronous, blocking version of this method.
 */
void
obex_message_access1_call_push_message (
    ObexMessageAccess1 *proxy,
    const gchar *arg_file,
    const gchar *arg_folder,
    GVariant *arg_args,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "PushMessage",
    g_variant_new ("(ss@a{sv})",
                   arg_file,
                   arg_folder,
                   arg_args),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * obex_message_access1_call_push_message_finish:
 * @proxy: A #ObexMessageAccess1Proxy.
 * @out_transfer: (out): Return location for return parameter or %NULL to ignore.
 * @out_properties: (out): Return location for return parameter or %NULL to ignore.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to obex_message_access1_call_push_message().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with obex_message_access1_call_push_message().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
obex_message_access1_call_push_message_finish (
    ObexMessageAccess1 *proxy,
    gchar **out_transfer,
    GVariant **out_properties,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(o@a{sv})",
                 out_transfer,
                 out_properties);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * obex_message_access1_call_push_message_sync:
 * @proxy: A #ObexMessageAccess1Proxy.
 * @arg_file: Argument to pass with the method invocation.
 * @arg_folder: Argument to pass with the method invocation.
 * @arg_args: Argument to pass with the method invocation.
 * @out_transfer: (out): Return location for return parameter or %NULL to ignore.
 * @out_properties: (out): Return location for return parameter or %NULL to ignore.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-bluez-obex-MessageAccess1.PushMessage">PushMessage()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See obex_message_access1_call_push_message() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
obex_message_access1_call_push_message_sync (
    ObexMessageAccess1 *proxy,
    const gchar *arg_file,
    const gchar *arg_folder,
    GVariant *arg_args,
    gchar **out_transfer,
    GVariant **out_properties,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "PushMessage",
    g_variant_new ("(ss@a{sv})",
                   arg_file,
                   arg_folder,
                   arg_args),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(o@a{sv})",
                 out_transfer,
                 out_properties);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * obex_message_access1_complete_set_folder:
 * @object: A #ObexMessageAccess1.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-bluez-obex-MessageAccess1.SetFolder">SetFolder()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
obex_message_access1_complete_set_folder (
    ObexMessageAccess1 *object,
    GDBusMethodInvocation *invocation)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("()"));
}

/**
 * obex_message_access1_complete_list_folders:
 * @object: A #ObexMessageAccess1.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 * @content: Parameter to return.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-bluez-obex-MessageAccess1.ListFolders">ListFolders()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
obex_message_access1_complete_list_folders (
    ObexMessageAccess1 *object,
    GDBusMethodInvocation *invocation,
    GVariant *content)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(@aa{sv})",
                   content));
}

/**
 * obex_message_access1_complete_list_messages:
 * @object: A #ObexMessageAccess1.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 * @messages: Parameter to return.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-bluez-obex-MessageAccess1.ListMessages">ListMessages()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
obex_message_access1_complete_list_messages (
    ObexMessageAccess1 *object,
    GDBusMethodInvocation *invocation,
    GVariant *messages)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(@a{oa{sv}})",
                   messages));
}

/**
 * obex_message_access1_complete_list_filter_fields:
 * @object: A #ObexMessageAccess1.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 * @fields: Parameter to return.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-bluez-obex-MessageAccess1.ListFilterFields">ListFilterFields()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
obex_message_access1_complete_list_filter_fields (
    ObexMessageAccess1 *object,
    GDBusMethodInvocation *invocation,
    const gchar *const *fields)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(^as)",
                   fields));
}

/**
 * obex_message_access1_complete_update_inbox:
 * @object: A #ObexMessageAccess1.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-bluez-obex-MessageAccess1.UpdateInbox">UpdateInbox()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
obex_message_access1_complete_update_inbox (
    ObexMessageAccess1 *object,
    GDBusMethodInvocation *invocation)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("()"));
}

/**
 * obex_message_access1_complete_push_message:
 * @object: A #ObexMessageAccess1.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 * @transfer: Parameter to return.
 * @properties: Parameter to return.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-bluez-obex-MessageAccess1.PushMessage">PushMessage()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
obex_message_access1_complete_push_message (
    ObexMessageAccess1 *object,
    GDBusMethodInvocation *invocation,
    const gchar *transfer,
    GVariant *properties)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(o@a{sv})",
                   transfer,
                   properties));
}

/* ------------------------------------------------------------------------ */

/**
 * ObexMessageAccess1Proxy:
 *
 * The #ObexMessageAccess1Proxy structure contains only private data and should only be accessed using the provided API.
 */

/**
 * ObexMessageAccess1ProxyClass:
 * @parent_class: The parent class.
 *
 * Class structure for #ObexMessageAccess1Proxy.
 */

struct _ObexMessageAccess1ProxyPrivate
{
  GData *qdata;
};

static void obex_message_access1_proxy_iface_init (ObexMessageAccess1Iface *iface);

#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
G_DEFINE_TYPE_WITH_CODE (ObexMessageAccess1Proxy, obex_message_access1_proxy, G_TYPE_DBUS_PROXY,
                         G_ADD_PRIVATE (ObexMessageAccess1Proxy)
                         G_IMPLEMENT_INTERFACE (TYPE_OBEX_MESSAGE_ACCESS1, obex_message_access1_proxy_iface_init));

#else
G_DEFINE_TYPE_WITH_CODE (ObexMessageAccess1Proxy, obex_message_access1_proxy, G_TYPE_DBUS_PROXY,
                         G_IMPLEMENT_INTERFACE (TYPE_OBEX_MESSAGE_ACCESS1, obex_message_access1_proxy_iface_init));

#endif
static void
obex_message_access1_proxy_finalize (GObject *object)
{
  ObexMessageAccess1Proxy *proxy = OBEX_MESSAGE_ACCESS1_PROXY (object);
  g_datalist_clear (&proxy->priv->qdata);
  G_OBJECT_CLASS (obex_message_access1_proxy_parent_class)->finalize (object);
}

static void
obex_message_access1_proxy_get_property (GObject      *object,
  guint         prop_id,
  GValue       *value,
  GParamSpec   *pspec G_GNUC_UNUSED)
{
}

static void
obex_message_access1_proxy_set_property (GObject      *object,
  guint         prop_id,
  const GValue *value,
  GParamSpec   *pspec G_GNUC_UNUSED)
{
}

static void
obex_message_access1_proxy_g_signal (GDBusProxy *proxy,
  const gchar *sender_name G_GNUC_UNUSED,
  const gchar *signal_name,
  GVariant *parameters)
{
  _ExtendedGDBusSignalInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  guint num_params;
  guint n;
  guint signal_id;
  info = (_ExtendedGDBusSignalInfo *) g_dbus_interface_info_lookup_signal ((GDBusInterfaceInfo *) &_obex_message_access1_interface_info.parent_struct, signal_name);
  if (info == NULL)
    return;
  num_params = g_variant_n_children (parameters);
  paramv = g_new0 (GValue, num_params + 1);
  g_value_init (&paramv[0], TYPE_OBEX_MESSAGE_ACCESS1);
  g_value_set_object (&paramv[0], proxy);
  g_variant_iter_init (&iter, parameters);
  n = 1;
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.args[n - 1];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, TYPE_OBEX_MESSAGE_ACCESS1);
  g_signal_emitv (paramv, signal_id, 0, NULL);
  for (n = 0; n < num_params + 1; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static void
obex_message_access1_proxy_g_properties_changed (GDBusProxy *_proxy,
  GVariant *changed_properties,
  const gchar *const *invalidated_properties)
{
  ObexMessageAccess1Proxy *proxy = OBEX_MESSAGE_ACCESS1_PROXY (_proxy);
  guint n;
  const gchar *key;
  GVariantIter *iter;
  _ExtendedGDBusPropertyInfo *info;
  g_variant_get (changed_properties, "a{sv}", &iter);
  while (g_variant_iter_next (iter, "{&sv}", &key, NULL))
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_obex_message_access1_interface_info.parent_struct, key);
      g_datalist_remove_data (&proxy->priv->qdata, key);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
  g_variant_iter_free (iter);
  for (n = 0; invalidated_properties[n] != NULL; n++)
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_obex_message_access1_interface_info.parent_struct, invalidated_properties[n]);
      g_datalist_remove_data (&proxy->priv->qdata, invalidated_properties[n]);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
}

static void
obex_message_access1_proxy_init (ObexMessageAccess1Proxy *proxy)
{
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
  proxy->priv = obex_message_access1_proxy_get_instance_private (proxy);
#else
  proxy->priv = G_TYPE_INSTANCE_GET_PRIVATE (proxy, TYPE_OBEX_MESSAGE_ACCESS1_PROXY, ObexMessageAccess1ProxyPrivate);
#endif

  g_dbus_proxy_set_interface_info (G_DBUS_PROXY (proxy), obex_message_access1_interface_info ());
}

static void
obex_message_access1_proxy_class_init (ObexMessageAccess1ProxyClass *klass)
{
  GObjectClass *gobject_class;
  GDBusProxyClass *proxy_class;

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize     = obex_message_access1_proxy_finalize;
  gobject_class->get_property = obex_message_access1_proxy_get_property;
  gobject_class->set_property = obex_message_access1_proxy_set_property;

  proxy_class = G_DBUS_PROXY_CLASS (klass);
  proxy_class->g_signal = obex_message_access1_proxy_g_signal;
  proxy_class->g_properties_changed = obex_message_access1_proxy_g_properties_changed;

#if GLIB_VERSION_MAX_ALLOWED < GLIB_VERSION_2_38
  g_type_class_add_private (klass, sizeof (ObexMessageAccess1ProxyPrivate));
#endif
}

static void
obex_message_access1_proxy_iface_init (ObexMessageAccess1Iface *iface)
{
}

/**
 * obex_message_access1_proxy_new:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-org-bluez-obex-MessageAccess1.top_of_page">org.bluez.obex.MessageAccess1</link>. See g_dbus_proxy_new() for more details.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call obex_message_access1_proxy_new_finish() to get the result of the operation.
 *
 * See obex_message_access1_proxy_new_sync() for the synchronous, blocking version of this constructor.
 */
void
obex_message_access1_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (TYPE_OBEX_MESSAGE_ACCESS1_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "org.bluez.obex.MessageAccess1", NULL);
}

/**
 * obex_message_access1_proxy_new_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to obex_message_access1_proxy_new().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with obex_message_access1_proxy_new().
 *
 * Returns: (transfer full) (type ObexMessageAccess1Proxy): The constructed proxy object or %NULL if @error is set.
 */
ObexMessageAccess1 *
obex_message_access1_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return OBEX_MESSAGE_ACCESS1 (ret);
  else
    return NULL;
}

/**
 * obex_message_access1_proxy_new_sync:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Synchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-org-bluez-obex-MessageAccess1.top_of_page">org.bluez.obex.MessageAccess1</link>. See g_dbus_proxy_new_sync() for more details.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See obex_message_access1_proxy_new() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type ObexMessageAccess1Proxy): The constructed proxy object or %NULL if @error is set.
 */
ObexMessageAccess1 *
obex_message_access1_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (TYPE_OBEX_MESSAGE_ACCESS1_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "org.bluez.obex.MessageAccess1", NULL);
  if (ret != NULL)
    return OBEX_MESSAGE_ACCESS1 (ret);
  else
    return NULL;
}


/**
 * obex_message_access1_proxy_new_for_bus:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Like obex_message_access1_proxy_new() but takes a #GBusType instead of a #GDBusConnection.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call obex_message_access1_proxy_new_for_bus_finish() to get the result of the operation.
 *
 * See obex_message_access1_proxy_new_for_bus_sync() for the synchronous, blocking version of this constructor.
 */
void
obex_message_access1_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (TYPE_OBEX_MESSAGE_ACCESS1_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "org.bluez.obex.MessageAccess1", NULL);
}

/**
 * obex_message_access1_proxy_new_for_bus_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to obex_message_access1_proxy_new_for_bus().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with obex_message_access1_proxy_new_for_bus().
 *
 * Returns: (transfer full) (type ObexMessageAccess1Proxy): The constructed proxy object or %NULL if @error is set.
 */
ObexMessageAccess1 *
obex_message_access1_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return OBEX_MESSAGE_ACCESS1 (ret);
  else
    return NULL;
}

/**
 * obex_message_access1_proxy_new_for_bus_sync:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Like obex_message_access1_proxy_new_sync() but takes a #GBusType instead of a #GDBusConnection.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See obex_message_access1_proxy_new_for_bus() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type ObexMessageAccess1Proxy): The constructed proxy object or %NULL if @error is set.
 */
ObexMessageAccess1 *
obex_message_access1_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (TYPE_OBEX_MESSAGE_ACCESS1_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "org.bluez.obex.MessageAccess1", NULL);
  if (ret != NULL)
    return OBEX_MESSAGE_ACCESS1 (ret);
  else
    return NULL;
}


/* ------------------------------------------------------------------------ */

/**
 * ObexMessageAccess1Skeleton:
 *
 * The #ObexMessageAccess1Skeleton structure contains only private data and should only be accessed using the provided API.
 */

/**
 * ObexMessageAccess1SkeletonClass:
 * @parent_class: The parent class.
 *
 * Class structure for #ObexMessageAccess1Skeleton.
 */

struct _ObexMessageAccess1SkeletonPrivate
{
  GValue *properties;
  GList *changed_properties;
  GSource *changed_properties_idle_source;
  GMainContext *context;
  GMutex lock;
};

static void
_obex_message_access1_skeleton_handle_method_call (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name,
  const gchar *method_name,
  GVariant *parameters,
  GDBusMethodInvocation *invocation,
  gpointer user_data)
{
  ObexMessageAccess1Skeleton *skeleton = OBEX_MESSAGE_ACCESS1_SKELETON (user_data);
  _ExtendedGDBusMethodInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  guint num_params;
  guint num_extra;
  guint n;
  guint signal_id;
  GValue return_value = G_VALUE_INIT;
  info = (_ExtendedGDBusMethodInfo *) g_dbus_method_invocation_get_method_info (invocation);
  g_assert (info != NULL);
  num_params = g_variant_n_children (parameters);
  num_extra = info->pass_fdlist ? 3 : 2;  paramv = g_new0 (GValue, num_params + num_extra);
  n = 0;
  g_value_init (&paramv[n], TYPE_OBEX_MESSAGE_ACCESS1);
  g_value_set_object (&paramv[n++], skeleton);
  g_value_init (&paramv[n], G_TYPE_DBUS_METHOD_INVOCATION);
  g_value_set_object (&paramv[n++], invocation);
  if (info->pass_fdlist)
    {
#ifdef G_OS_UNIX
      g_value_init (&paramv[n], G_TYPE_UNIX_FD_LIST);
      g_value_set_object (&paramv[n++], g_dbus_message_get_unix_fd_list (g_dbus_method_invocation_get_message (invocation)));
#else
      g_assert_not_reached ();
#endif
    }
  g_variant_iter_init (&iter, parameters);
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.in_args[n - num_extra];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, TYPE_OBEX_MESSAGE_ACCESS1);
  g_value_init (&return_value, G_TYPE_BOOLEAN);
  g_signal_emitv (paramv, signal_id, 0, &return_value);
  if (!g_value_get_boolean (&return_value))
    g_dbus_method_invocation_return_error (invocation, G_DBUS_ERROR, G_DBUS_ERROR_UNKNOWN_METHOD, "Method %s is not implemented on interface %s", method_name, interface_name);
  g_value_unset (&return_value);
  for (n = 0; n < num_params + num_extra; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static GVariant *
_obex_message_access1_skeleton_handle_get_property (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name G_GNUC_UNUSED,
  const gchar *property_name,
  GError **error,
  gpointer user_data)
{
  ObexMessageAccess1Skeleton *skeleton = OBEX_MESSAGE_ACCESS1_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  GVariant *ret;
  ret = NULL;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_obex_message_access1_interface_info.parent_struct, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      g_value_init (&value, pspec->value_type);
      g_object_get_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      ret = g_dbus_gvalue_to_gvariant (&value, G_VARIANT_TYPE (info->parent_struct.signature));
      g_value_unset (&value);
    }
  return ret;
}

static gboolean
_obex_message_access1_skeleton_handle_set_property (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name G_GNUC_UNUSED,
  const gchar *property_name,
  GVariant *variant,
  GError **error,
  gpointer user_data)
{
  ObexMessageAccess1Skeleton *skeleton = OBEX_MESSAGE_ACCESS1_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  gboolean ret;
  ret = FALSE;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_obex_message_access1_interface_info.parent_struct, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      if (info->use_gvariant)
        g_value_set_variant (&value, variant);
      else
        g_dbus_gvariant_to_gvalue (variant, &value);
      g_object_set_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      g_value_unset (&value);
      ret = TRUE;
    }
  return ret;
}

static const GDBusInterfaceVTable _obex_message_access1_skeleton_vtable =
{
  _obex_message_access1_skeleton_handle_method_call,
  _obex_message_access1_skeleton_handle_get_property,
  _obex_message_access1_skeleton_handle_set_property,
  {NULL}
};

static GDBusInterfaceInfo *
obex_message_access1_skeleton_dbus_interface_get_info (GDBusInterfaceSkeleton *skeleton G_GNUC_UNUSED)
{
  return obex_message_access1_interface_info ();
}

static GDBusInterfaceVTable *
obex_message_access1_skeleton_dbus_interface_get_vtable (GDBusInterfaceSkeleton *skeleton G_GNUC_UNUSED)
{
  return (GDBusInterfaceVTable *) &_obex_message_access1_skeleton_vtable;
}

static GVariant *
obex_message_access1_skeleton_dbus_interface_get_properties (GDBusInterfaceSkeleton *_skeleton)
{
  ObexMessageAccess1Skeleton *skeleton = OBEX_MESSAGE_ACCESS1_SKELETON (_skeleton);

  GVariantBuilder builder;
  guint n;
  g_variant_builder_init (&builder, G_VARIANT_TYPE ("a{sv}"));
  if (_obex_message_access1_interface_info.parent_struct.properties == NULL)
    goto out;
  for (n = 0; _obex_message_access1_interface_info.parent_struct.properties[n] != NULL; n++)
    {
      GDBusPropertyInfo *info = _obex_message_access1_interface_info.parent_struct.properties[n];
      if (info->flags & G_DBUS_PROPERTY_INFO_FLAGS_READABLE)
        {
          GVariant *value;
          value = _obex_message_access1_skeleton_handle_get_property (g_dbus_interface_skeleton_get_connection (G_DBUS_INTERFACE_SKELETON (skeleton)), NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "org.bluez.obex.MessageAccess1", info->name, NULL, skeleton);
          if (value != NULL)
            {
              g_variant_take_ref (value);
              g_variant_builder_add (&builder, "{sv}", info->name, value);
              g_variant_unref (value);
            }
        }
    }
out:
  return g_variant_builder_end (&builder);
}

static void
obex_message_access1_skeleton_dbus_interface_flush (GDBusInterfaceSkeleton *_skeleton)
{
}

static void obex_message_access1_skeleton_iface_init (ObexMessageAccess1Iface *iface);
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
G_DEFINE_TYPE_WITH_CODE (ObexMessageAccess1Skeleton, obex_message_access1_skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_ADD_PRIVATE (ObexMessageAccess1Skeleton)
                         G_IMPLEMENT_INTERFACE (TYPE_OBEX_MESSAGE_ACCESS1, obex_message_access1_skeleton_iface_init));

#else
G_DEFINE_TYPE_WITH_CODE (ObexMessageAccess1Skeleton, obex_message_access1_skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_IMPLEMENT_INTERFACE (TYPE_OBEX_MESSAGE_ACCESS1, obex_message_access1_skeleton_iface_init));

#endif
static void
obex_message_access1_skeleton_finalize (GObject *object)
{
  ObexMessageAccess1Skeleton *skeleton = OBEX_MESSAGE_ACCESS1_SKELETON (object);
  g_list_free_full (skeleton->priv->changed_properties, (GDestroyNotify) _changed_property_free);
  if (skeleton->priv->changed_properties_idle_source != NULL)
    g_source_destroy (skeleton->priv->changed_properties_idle_source);
  g_main_context_unref (skeleton->priv->context);
  g_mutex_clear (&skeleton->priv->lock);
  G_OBJECT_CLASS (obex_message_access1_skeleton_parent_class)->finalize (object);
}

static void
obex_message_access1_skeleton_init (ObexMessageAccess1Skeleton *skeleton)
{
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
  skeleton->priv = obex_message_access1_skeleton_get_instance_private (skeleton);
#else
  skeleton->priv = G_TYPE_INSTANCE_GET_PRIVATE (skeleton, TYPE_OBEX_MESSAGE_ACCESS1_SKELETON, ObexMessageAccess1SkeletonPrivate);
#endif

  g_mutex_init (&skeleton->priv->lock);
  skeleton->priv->context = g_main_context_ref_thread_default ();
}

static void
obex_message_access1_skeleton_class_init (ObexMessageAccess1SkeletonClass *klass)
{
  GObjectClass *gobject_class;
  GDBusInterfaceSkeletonClass *skeleton_class;

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize = obex_message_access1_skeleton_finalize;

  skeleton_class = G_DBUS_INTERFACE_SKELETON_CLASS (klass);
  skeleton_class->get_info = obex_message_access1_skeleton_dbus_interface_get_info;
  skeleton_class->get_properties = obex_message_access1_skeleton_dbus_interface_get_properties;
  skeleton_class->flush = obex_message_access1_skeleton_dbus_interface_flush;
  skeleton_class->get_vtable = obex_message_access1_skeleton_dbus_interface_get_vtable;

#if GLIB_VERSION_MAX_ALLOWED < GLIB_VERSION_2_38
  g_type_class_add_private (klass, sizeof (ObexMessageAccess1SkeletonPrivate));
#endif
}

static void
obex_message_access1_skeleton_iface_init (ObexMessageAccess1Iface *iface)
{
}

/**
 * obex_message_access1_skeleton_new:
 *
 * Creates a skeleton object for the D-Bus interface <link linkend="gdbus-interface-org-bluez-obex-MessageAccess1.top_of_page">org.bluez.obex.MessageAccess1</link>.
 *
 * Returns: (transfer full) (type ObexMessageAccess1Skeleton): The skeleton object.
 */
ObexMessageAccess1 *
obex_message_access1_skeleton_new (void)
{
  return OBEX_MESSAGE_ACCESS1 (g_object_new (TYPE_OBEX_MESSAGE_ACCESS1_SKELETON, NULL));
}

