/*
 * Generated by gdbus-codegen 2.40.2. DO NOT EDIT.
 *
 * The license of this code is the same as for the source it was derived from.
 */

#ifndef __MAPMSG_H__
#define __MAPMSG_H__

#include <gio/gio.h>

G_BEGIN_DECLS


/* ------------------------------------------------------------------------ */
/* Declarations for org.bluez.obex.Message1 */

#define TYPE_OBEX_MESSAGE1 (obex_message1_get_type ())
#define OBEX_MESSAGE1(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_OBEX_MESSAGE1, ObexMessage1))
#define IS_OBEX_MESSAGE1(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_OBEX_MESSAGE1))
#define OBEX_MESSAGE1_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE ((o), TYPE_OBEX_MESSAGE1, ObexMessage1Iface))

struct _ObexMessage1;
typedef struct _ObexMessage1 ObexMessage1;
typedef struct _ObexMessage1Iface ObexMessage1Iface;

struct _ObexMessage1Iface
{
  GTypeInterface parent_iface;


  gboolean (*handle_get) (
    ObexMessage1 *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_targetfile,
    gboolean arg_attachment);

  gboolean (*handle_get_properties) (
    ObexMessage1 *object,
    GDBusMethodInvocation *invocation);

  gboolean (*handle_set_property) (
    ObexMessage1 *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_unnamed_arg0,
    GVariant *arg_unnamed_arg1);

  void (*property_changed) (
    ObexMessage1 *object,
    const gchar *arg_unnamed_arg0,
    GVariant *arg_unnamed_arg1);

};

GType obex_message1_get_type (void) G_GNUC_CONST;

GDBusInterfaceInfo *obex_message1_interface_info (void);
guint obex_message1_override_properties (GObjectClass *klass, guint property_id_begin);


/* D-Bus method call completion functions: */
void obex_message1_complete_get_properties (
    ObexMessage1 *object,
    GDBusMethodInvocation *invocation,
    GVariant *unnamed_arg0);

void obex_message1_complete_set_property (
    ObexMessage1 *object,
    GDBusMethodInvocation *invocation);

void obex_message1_complete_get (
    ObexMessage1 *object,
    GDBusMethodInvocation *invocation,
    const gchar *transfer,
    GVariant *properties);



/* D-Bus signal emissions functions: */
void obex_message1_emit_property_changed (
    ObexMessage1 *object,
    const gchar *arg_unnamed_arg0,
    GVariant *arg_unnamed_arg1);



/* D-Bus method calls: */
void obex_message1_call_get_properties (
    ObexMessage1 *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean obex_message1_call_get_properties_finish (
    ObexMessage1 *proxy,
    GVariant **out_unnamed_arg0,
    GAsyncResult *res,
    GError **error);

gboolean obex_message1_call_get_properties_sync (
    ObexMessage1 *proxy,
    GVariant **out_unnamed_arg0,
    GCancellable *cancellable,
    GError **error);

void obex_message1_call_set_property (
    ObexMessage1 *proxy,
    const gchar *arg_unnamed_arg0,
    GVariant *arg_unnamed_arg1,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean obex_message1_call_set_property_finish (
    ObexMessage1 *proxy,
    GAsyncResult *res,
    GError **error);

gboolean obex_message1_call_set_property_sync (
    ObexMessage1 *proxy,
    const gchar *arg_unnamed_arg0,
    GVariant *arg_unnamed_arg1,
    GCancellable *cancellable,
    GError **error);

void obex_message1_call_get (
    ObexMessage1 *proxy,
    const gchar *arg_targetfile,
    gboolean arg_attachment,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean obex_message1_call_get_finish (
    ObexMessage1 *proxy,
    gchar **out_transfer,
    GVariant **out_properties,
    GAsyncResult *res,
    GError **error);

gboolean obex_message1_call_get_sync (
    ObexMessage1 *proxy,
    const gchar *arg_targetfile,
    gboolean arg_attachment,
    gchar **out_transfer,
    GVariant **out_properties,
    GCancellable *cancellable,
    GError **error);



/* ---- */

#define TYPE_OBEX_MESSAGE1_PROXY (obex_message1_proxy_get_type ())
#define OBEX_MESSAGE1_PROXY(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_OBEX_MESSAGE1_PROXY, ObexMessage1Proxy))
#define OBEX_MESSAGE1_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), TYPE_OBEX_MESSAGE1_PROXY, ObexMessage1ProxyClass))
#define OBEX_MESSAGE1_PROXY_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), TYPE_OBEX_MESSAGE1_PROXY, ObexMessage1ProxyClass))
#define IS_OBEX_MESSAGE1_PROXY(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_OBEX_MESSAGE1_PROXY))
#define IS_OBEX_MESSAGE1_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), TYPE_OBEX_MESSAGE1_PROXY))

typedef struct _ObexMessage1Proxy ObexMessage1Proxy;
typedef struct _ObexMessage1ProxyClass ObexMessage1ProxyClass;
typedef struct _ObexMessage1ProxyPrivate ObexMessage1ProxyPrivate;

struct _ObexMessage1Proxy
{
  /*< private >*/
  GDBusProxy parent_instance;
  ObexMessage1ProxyPrivate *priv;
};

struct _ObexMessage1ProxyClass
{
  GDBusProxyClass parent_class;
};

GType obex_message1_proxy_get_type (void) G_GNUC_CONST;

void obex_message1_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
ObexMessage1 *obex_message1_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error);
ObexMessage1 *obex_message1_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);

void obex_message1_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
ObexMessage1 *obex_message1_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error);
ObexMessage1 *obex_message1_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);


/* ---- */

#define TYPE_OBEX_MESSAGE1_SKELETON (obex_message1_skeleton_get_type ())
#define OBEX_MESSAGE1_SKELETON(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_OBEX_MESSAGE1_SKELETON, ObexMessage1Skeleton))
#define OBEX_MESSAGE1_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), TYPE_OBEX_MESSAGE1_SKELETON, ObexMessage1SkeletonClass))
#define OBEX_MESSAGE1_SKELETON_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), TYPE_OBEX_MESSAGE1_SKELETON, ObexMessage1SkeletonClass))
#define IS_OBEX_MESSAGE1_SKELETON(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_OBEX_MESSAGE1_SKELETON))
#define IS_OBEX_MESSAGE1_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), TYPE_OBEX_MESSAGE1_SKELETON))

typedef struct _ObexMessage1Skeleton ObexMessage1Skeleton;
typedef struct _ObexMessage1SkeletonClass ObexMessage1SkeletonClass;
typedef struct _ObexMessage1SkeletonPrivate ObexMessage1SkeletonPrivate;

struct _ObexMessage1Skeleton
{
  /*< private >*/
  GDBusInterfaceSkeleton parent_instance;
  ObexMessage1SkeletonPrivate *priv;
};

struct _ObexMessage1SkeletonClass
{
  GDBusInterfaceSkeletonClass parent_class;
};

GType obex_message1_skeleton_get_type (void) G_GNUC_CONST;

ObexMessage1 *obex_message1_skeleton_new (void);


G_END_DECLS

#endif /* __MAPMSG_H__ */
